# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])

In [3]:
a

array([2, 3, 4])

In [4]:
a.dtype

dtype('int64')

In [5]:
b = np.array([1.2, 3.5, 5.1])

In [6]:
b.dtype

dtype('float64')

In [8]:
a = np.array(1,2,3,4)

ValueError: only 2 non-keyword arguments accepted

In [9]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
b = np.array([(1.5,2,3), (4,5,6)])
print(b)

[[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]


In [11]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [12]:
c=np.ones( (2,3,4), dtype=np.int16 )  
print(c)
print(c.shape)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
(2, 3, 4)


In [13]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [14]:
[i for i in range(10,30,5)]

[10, 15, 20, 25]

In [15]:
np.arange( 0, 2, 0.3 ) 

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [16]:
b = np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [17]:
A = np.array( [[1,1], [0,1]] )
print(A)
print()
B = np.array( [[2,0], [3,4]] )
print(B)
print()
print(A*B)
print()
print(A.dot(B))
print()
print(np.dot(A, B))

[[1 1]
 [0 1]]

[[2 0]
 [3 4]]

[[2 0]
 [0 4]]

[[5 4]
 [3 4]]

[[5 4]
 [3 4]]


In [18]:
np.vstack((A,B))

array([[1, 1],
       [0, 1],
       [2, 0],
       [3, 4]])

In [19]:
b = np.random.random((2,3))
print(b)

[[ 0.05513705  0.57629242  0.50217345]
 [ 0.76801171  0.104212    0.06037641]]


In [ ]:
b.sum(axis=0) 

## Copies and Views

#### No Copy at All

In [ ]:
a = np.arange(12)
b = a            # no new object is created
print(a)
print(b)

In [ ]:
print(b is a)           # a and b are two names for the same ndarray object
b.shape = 3,4    # changes the shape of a
a.shape

In [ ]:
print(a)
print(b)
print('---')
print(id(a))
print(id(b))

#### View or Shallow Copy

In [ ]:
c = a.view()
print(c is a)
print(c)

In [ ]:
print(id(c))
print(id(c.base))
print(id(a))

In [ ]:
c.base[0,0]=56
c[0,1] = 1000
c.shape = 2,6  
print(c)
print(a)

#### Deep Copy

In [ ]:
d = a.copy()
print(d is a)
print(d.base is a)

In [ ]:
d[0,0] = 9999
print(d)
print(a)